/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thoughtworks.domain_driven_design;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Driver driver = new Driver();
        driver.drive();
    }
}
